<?php
			$optionsArray = array( 'totals' => array( 'acad_group' => array( 'totalsType' => '' ),
'0 units' => array( 'totalsType' => '' ),
'1-2 units' => array( 'totalsType' => '' ),
'3-5 units' => array( 'totalsType' => '' ),
'6-8 units' => array( 'totalsType' => '' ),
'9-11 units' => array( 'totalsType' => '' ),
'12-14 units' => array( 'totalsType' => '' ),
'15 units above' => array( 'totalsType' => '' ),
'total' => array( 'totalsType' => '' ),
'term_id' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'acad_group',
'0 units',
'1-2 units',
'3-5 units',
'6-8 units',
'9-11 units',
'12-14 units',
'15 units above',
'total',
'term_id' ),
'exportFields' => array( 'acad_group',
'0 units',
'1-2 units',
'3-5 units',
'6-8 units',
'9-11 units',
'12-14 units',
'15 units above',
'total',
'term_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'acad_group' => array( 'export_field' ),
'0 units' => array( 'export_field1' ),
'1-2 units' => array( 'export_field2' ),
'3-5 units' => array( 'export_field3' ),
'6-8 units' => array( 'export_field4' ),
'9-11 units' => array( 'export_field5' ),
'12-14 units' => array( 'export_field6' ),
'15 units above' => array( 'export_field7' ),
'total' => array( 'export_field8' ),
'term_id' => array( 'export_field9' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'acad_group',
'type' => 'export_field' ),
'export_field1' => array( 'field' => '0 units',
'type' => 'export_field' ),
'export_field2' => array( 'field' => '1-2 units',
'type' => 'export_field' ),
'export_field3' => array( 'field' => '3-5 units',
'type' => 'export_field' ),
'export_field4' => array( 'field' => '6-8 units',
'type' => 'export_field' ),
'export_field5' => array( 'field' => '9-11 units',
'type' => 'export_field' ),
'export_field6' => array( 'field' => '12-14 units',
'type' => 'export_field' ),
'export_field7' => array( 'field' => '15 units above',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'total',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'term_id',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>